apiVersion: v1
kind: Service
metadata:
  name: spring-sample-app-k8s
  labels:
    app: spring-sample-app-k8s
spec:
  selector:
    app: spring-sample-app-k8s
  ports:
    - protocol: "TCP"
      port: 8080
      name: http
      targetPort: 8080
  type: ClusterIP